### ISSUE TITLE
Errors when I install fasta36 on ubuntu36

### ISSUE THREAD

**Issue by wangzhennan14** [wrpearson/fasta36#10]
Hi,
    When I install fasta36 on ubuntu18.04, there was an error as follow:
    FSEEKO -DSAMP_STATS -DPGM_DOC -DUSE_MMAP  -D_LARGEFILE64_SOURCE  -DBIG_LIB64 -c dropnnw2.c -o droplnw_sse.o
dropnnw2.c: In function ‘do_work’:
dropnnw2.c:578:18: error: ‘OVERFLOW’ undeclared (first use in this function); did you mean ‘OVERFLOW_SCORE’?
     if (score == OVERFLOW) {
                  ^~~~~~~~
                  OVERFLOW_SCORE
dropnnw2.c:578:18: note: each undeclared identifier is reported only once for each function it appears in
../make/Makefile.fcom:244: recipe for target 'droplnw_sse.o' failed
make: *** [droplnw_sse.o] Error 1
      What is the matter?  And how can I solve this? Could you give me some advices?
                                                                                                           Wang

**Comment by wrpearson** [comment]
This problem has been fixed on the current branch, fasta v36.3.8

Bill Pearson
