### ISSUE TITLE
ssearch36 segfaults above ~62k peptide sequences

### ISSUE THREAD

**Issue by petersbr** [wrpearson/fasta36#13]
Hello,

I cannot get ssearch36 to run without a rapid segfault (older .e version) or as a floating point exception (current github master) on my local server.   Is this a known problem?

I am wondering if there is a character limit somewhere as the actual peptide sequence count required to observe the error changes a bit with different random samplings without replacement of a large peptide sequence pool.  It runs without error on smaller or if I split the library into smaller chunks.

```ssearch36 -T 7 -d 0 -m 9 -z -1 tst.65000 tst.65000```

The tst.65000 files contain peptide sequences generated by gffread's translation of CDS features of mRNAs in the ensembl plants maize reference file.

**Comment by wrpearson** [comment]
No, I do not expect ssearch36 to seg-fault.

If you could provide me with the files that are causing the problem, I can probably figure out what is going wrong.

I might be able to do it if you simply run "gdb ssearch36 core.*" and type "w" to tell me where it seg-faulted.

ssearch36 (and the other fasta programs) should not have a problem searching libraries with 10's--100's of millions of sequences.

Bill Pearson


Begin forwarded message:

**Comment by petersbr** [comment]
It is taking conda a while to install gdb but I do have the trace from valgrind below in case it helps while I wait.
I am currently on this (Linux/3.10.0-514.26.2.el7.x86_64 CentOS Linux/7.3.1611 glibc/2.17) machine but will try an older CentOS6 one to see if that changes anything.
```
ssearch36 -b 5 -m 0 -z -1 tst.65000 tst.65000
SSEARCH performs a Smith-Waterman search
 version 36.3.8g Aug, 2018
Please cite:
 T. F. Smith and M. S. Waterman, (1981) J. Mol. Biol. 147:195-197;
 W.R. Pearson (1991) Genomics 11:635-650

==24734== Use of uninitialised value of size 8
==24734==    at 0x42625D: addhistz (scaleswn.c:1877)
==24734==    by 0x40D800: save_best2 (compacc2e.c:2800)
==24734==    by 0x40346C: seqr_chain_work (comp_lib9.c:2914)
==24734==    by 0x404632: main (comp_lib9.c:1018)
==24734==
==24734== Use of uninitialised value of size 8
==24734==    at 0x42628F: addhistz (scaleswn.c:1886)
==24734==    by 0x40D800: save_best2 (compacc2e.c:2800)
==24734==    by 0x40346C: seqr_chain_work (comp_lib9.c:2914)
==24734==    by 0x404632: main (comp_lib9.c:1018)
==24734==
==24734== Invalid read of size 4
==24734==    at 0x42628F: addhistz (scaleswn.c:1886)
==24734==    by 0x40D800: save_best2 (compacc2e.c:2800)
==24734==    by 0x40346C: seqr_chain_work (comp_lib9.c:2914)
==24734==    by 0x404632: main (comp_lib9.c:1018)
==24734==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==24734==
==24734==
==24734== Process terminating with default action of signal 11 (SIGSEGV)
==24734==  Access not within mapped region at address 0x0
==24734==    at 0x42628F: addhistz (scaleswn.c:1886)
==24734==    by 0x40D800: save_best2 (compacc2e.c:2800)
==24734==    by 0x40346C: seqr_chain_work (comp_lib9.c:2914)
==24734==    by 0x404632: main (comp_lib9.c:1018)
==24734==  If you believe this happened as a result of a stack
==24734==  overflow in your program's main thread (unlikely but
==24734==  possible), you can try to increase the size of the
==24734==  main thread stack using the --main-stacksize= flag.
==24734==  The main thread stack size used in this run was 16777216.
==24734==
==24734== HEAP SUMMARY:
==24734==     in use at exit: 148,256,580 bytes in 423 blocks
==24734==   total heap usage: 428 allocs, 5 frees, 148,294,716 bytes allocated
==24734==
==24734== LEAK SUMMARY:
==24734==    definitely lost: 40 bytes in 1 blocks
==24734==    indirectly lost: 0 bytes in 0 blocks
==24734==      possibly lost: 37,108,489 bytes in 72 blocks
==24734==    still reachable: 111,148,051 bytes in 350 blocks
==24734==         suppressed: 0 bytes in 0 blocks
==24734== Rerun with --leak-check=full to see details of leaked memory
==24734==
==24734== For counts of detected and suppressed errors, rerun with: -v
==24734== Use --track-origins=yes to see where uninitialised values come from
==24734== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by petersbr** [comment]
fasta36 processes the inputs just fine.  I don't know if it matters, but the peptide sequences can be pretty ugly if there are problems with the GFF input, meaning that there can be numerous asterisks representing stops throughout.

Here is the gdb for the core dumped from a colleagues copy:
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from fasta-36.3.8e/bin/ssearch36...done.
[New LWP 31668]
[New LWP 31669]
[New LWP 31671]
[New LWP 31670]
[New LWP 31674]
[New LWP 31672]
[New LWP 31673]
[New LWP 31675]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fasta-36.3.8e/bin/ssearch36 -T 7 -d 0'.
Program terminated with signal 8, Arithmetic exception.
#0  0x0000000000421917 in addhistz (zs=<optimized out>, histp=0x7ffe361762c0) at scaleswn.c:1826
1826      histp->hist_a[ih]++;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.5.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) where
#0  0x0000000000421917 in addhistz (zs=<optimized out>, histp=0x7ffe361762c0) at scaleswn.c:1826
#1  0x000000000040b290 in save_best2 (lib_bhead_p=0x20d8840, m_msp=0x7ffe361715f0, ppst=0x7ffe36176800, ldb=<optimized out>, fdata=0x0, histp=0x7ffe361762c0, pstat_voidp=0x7ffe361764f0, 
    s_info=0x7ffe36176280) at compacc2e.c:2793
#2  0x00000000004032af in seqr_chain_work (aa0=<optimized out>, aa0s=<optimized out>, lib_bhead_p=0x20d88d0, getlib_info=0x240e6a0, m_bufi_p=<optimized out>, m_msp=0x7ffe361715f0, 
    ppst=0x7ffe36176800, pstat_void=0x7ffe361764f0, ldb=0x7ffe36176268, histp=0x7ffe361762c0, s_info=0x7ffe36176280, best_seqs=0x7f481dc24010, best_mseqs=0x7f481d805010, 
    best=0x7f481dee40b0, fdata=0x0) at comp_lib9.c:2898
#3  0x00000000004047a3 in main (argc=45000, argv=0x7f481f4c4011) at comp_lib9.c:1007
(gdb) 
```

**Comment by wrpearson** [comment]
I don't think it will matter which Centos you run on -- I use Centos 6 and 7.  

The info you sent suggests there is a problem with the statistics routines being used.  This can happen when the distribution of lengths is different from my assumptions.

Try doing the large search with a -z 0 or -z 3 and see if things run (I would not trust the statistics with -z 0). My suspicion is that things will run.  You might then check to see what the distributions of lengths are for in your library.  If there is very little variation (less than a factor of 2 between longest and shortest)  then you will need to use -z 0 or -z 3.

Bill Pearson

**Comment by wrpearson** [comment]
In general, lots of '*'s should not cause problems (just like lots of 'X's should not), unless you are producing hundreds or thousands of sequences with < 5 length.

What I am confused by is your argc=45000 --- can you send me your actual command line?

Since the only non-optional arguments are the query.file and the library.file, it's hard for me to understand why argc would ever be > 10.

I still think this has something to do with the range of library sequence lengths.

Bill Pearson

Begin forwarded message:

**Comment by petersbr** [comment]
Both proposed changes work.  In fact, running it with anything but the "no stats" option "-z -1" works.

I don't know why argc is like that, I've been using:
```
ssearch36 -T 7 -d 0 -m 9 -z -1  maize.pep maize.pep
```
with various versions.

I think you have me back in business on my end.  
```
There are 92,906 sequences in maize.pep
Lengths: mean =   456aa median =   346aa
         max  = 5,268aa min    =     2aa
The total number of residues is 42,397,131
```

**Comment by petersbr** [comment]
Thank you very much for your unexpectedly rapid help!  You can let me know if you want this closed or left as a reminder in case you want to try to catch the segfault scenario in a future version.

**Comment by wrpearson** [comment]
If you could either send me your sequences, or use the '-R result.file' option and send it to me, I can take a look at things.

Bill Pearson

Begin forwarded message:

**Comment by wrpearson** [comment]
You are probably better off using -z 0 (or -z 3) than -z -1.  Over the years the programs may have shifted to becoming more dependent on statistics, which -z -1 does not provide.  But if it works (and you don't care about statistics), good luck.

Bill Pearson

**Comment by petersbr** [comment]
Test sequence file:
[tst.65000.gz](https://github.com/wrpearson/fasta36/files/2362574/tst.65000.gz)

Code modification didn't seem to help when I recompiled (here is the section with the change made):
```
fasta36/bin/ssearch36 -T 7 -d 0 -m 9 -z -1 tst.65000 tst.65000
```

```
/* histogram will go from z-scores of 20 .. 100 with mean 50 and z=10 */

void
inithistz(int mh, struct hist_str *histp, double zs_off)
{
  int i, izs_off;

  izs_off = (int)(zs_off + 0.5);

  histp->z_calls = 0;

  histp->min_hist = 20 + izs_off*10;
  histp->max_hist = 120 + izs_off * 10;

  histp->histint = (int)
    ((double)(histp->max_hist - histp->min_hist + 2)/(double)mh+0.5);
  
  if (histp->histint < 1) {
    histp->histint = 1;
  }
  
  histp->maxh = (int)
    ((double)(histp->max_hist - histp->min_hist + 2)/(double)histp->histint+0.5);

  if (histp->hist_a==NULL) {
    if ((histp->hist_a=(int *)calloc((size_t)histp->maxh,sizeof(int)))==
	NULL) {
      fprintf(stderr," cannot allocate %d for histogram\n",histp->maxh);
      histp->histflg = 0;
    }
    else histp->histflg = 1;
  }
  else {
    for (i=0; i<histp->maxh; i++) histp->hist_a[i]=0;
  }
  histp->entries = 0;
}
```

I am not sure why the original author of the pipeline I am working on disabled the statistics, I have no problem with keeping them.

gdb with the code change:
```
gdb fasta36/bin/ssearch36 core.3273 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
Reading symbols from fasta36/bin/ssearch36...done.
[New LWP 3273]
[New LWP 3275]
[New LWP 3274]
[New LWP 3279]
[New LWP 3277]
[New LWP 3278]
[New LWP 3280]
[New LWP 3276]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fasta36/bin/ssearch36'.
Program terminated with signal 8, Arithmetic exception.
#0  0x000000000042628c in addhistz (zs=<optimized out>, histp=histp@entry=0x7fff0218e300) at scaleswn.c:1889
1889      ih = (zi - histp->min_hist)/histp->histint;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.5.x86_64
(gdb) where
#0  0x000000000042628c in addhistz (zs=<optimized out>, histp=histp@entry=0x7fff0218e300) at scaleswn.c:1889
#1  0x000000000040d801 in save_best2 (lib_bhead_p=0x1f731d0, m_msp=m_msp@entry=0x7fff02189630, ppst=ppst@entry=0x7fff0218e840, ldb=ldb@entry=0x7fff0218e2a8, fdata=fdata@entry=0x0, 
    histp=histp@entry=0x7fff0218e300, pstat_voidp=0x7fff0218e530, s_info=0x7fff0218e2c0) at compacc2e.c:2800
#2  0x000000000040346d in seqr_chain_work (aa0=aa0@entry=0x7fff02190600, aa0s=aa0s@entry=0x0, lib_bhead_p=<optimized out>, getlib_info=getlib_info@entry=0x22a86a0, 
    m_bufi_p=m_bufi_p@entry=0x7fff0218e7f0, m_msp=m_msp@entry=0x7fff02189630, ppst=0x7fff0218e840, pstat_void=0x7fff0218e530, ldb=0x7fff0218e2a8, histp=0x7fff0218e300, 
    s_info=0x7fff0218e2c0, best_seqs=0x7f9ef2257010, best_mseqs=0x7f9ef1e38010, best=0x7f9ef25170b0, fdata=0x0) at comp_lib9.c:2914
#3  0x0000000000404633 in main (argc=<optimized out>, argv=<optimized out>) at comp_lib9.c:1018
```

Thanks again

**Comment by wrpearson** [comment]
Thank you for sending me the test file.

I have run the sequences you sent, using exactly the same command line parameters, without any difficulties (and without changing the -z statistics option) on both linux Centos 6 and Centos 7 machines.

If I can find a place where the error occurs, I will certainly fix it.
'
Bill Pearson

Begin forwarded message:

**Comment by petersbr** [comment]
Adding a comment that Bill couldn't reproduce the segfault behavior when supplied with the sequences which suggests that it is some sort of difference in the system environments.  So this was a bit of a red herring for him but he did provide a work-around that let me get past it, even in my computing environment.
