### ISSUE TITLE
*** error [comp_lib9.c:642] cannot open library

### ISSUE THREAD

**Issue by Amrithasuresh** [wrpearson/fasta36#14]
Hi,

I have installed FASTA in MacOS and ran with the following command in terminal and it works well.

`fasta36 -s BP62 -p fasta1.fa fasta2.fa | grep identity`

 But, when I try to use the fasta36 in a python script I get the following error

`*** error [comp_lib9.c:642] cannot open library ../fastax`

I have the following path 

`export PATH="/Users/suresh/softwares/fasta36/bin:$PATH"`

Do I need to provide the path of the library file? Can anyone suggest me?

Thank you for your time.

**Comment by wrpearson** [comment]
There is no program called "fastax".

You can see the programs in the ../bin directory, they include "fasta36" and "fastx36" (which compares a DNA sequence to a protein database), but no "fastax".

However, the error message you are seeing suggests that you are not finding either the query sequence or the database file.  I suggest that you print out the command that your python script is executing, and see if you can execute it from the terminal shell.

Bill Pearson


Begin forwarded message:

**Comment by Amrithasuresh** [comment]
Thank you very much for prompt reply. 

I cross check both the query and database file exists in the path. Perhaps, I guess I found the issue. I had a folder named `fasta_matrix` in the path of the query file. I just created a  different folder with different name. It works now. I am not sure the exact reason. 

Thank you! Bill Pearson.
