### ISSUE TITLE
Sliding window searches

### ISSUE THREAD

**Issue by susheelbhanu** [wrpearson/fasta36#16]
Dear Bill, 

Firstly, thank you for the very nice tool. The following website http://www.allergenonline.org/databasefasta.shtml, seems to be using it with what is called a "80-mer sliding window" approach. 

Is this something that can be implemented via your tool? I noticed that you have a "-v" option for window shuffling, but I presume this is not the same as the former. 

Thank you,
Susheel

**Comment by wrpearson** [comment]
The programs in the FASTA package are designed to do various kinds of local or global alignments.  Sliding windows are not part of FASTA (the -v option sets a shuffle window length, for producing random sequences for statistical analysis).
