### ISSUE TITLE
ggsearch

### ISSUE THREAD

**Issue by gaboentropy** [wrpearson/fasta36#17]
Neither ggsearch nor glsearch were built when I compiled in mac (also hard to figure out which Makefile to use for OSX Mojave, lots of trial and error)

**Comment by gaboentropy** [comment]
Sorry. I figured it out. Using Makefile.osx86_64 built everything.

**Comment by wrpearson** [comment]
I'm sorry you had a problem.  The correct command to make the programs on MacOS (I have not yet tested on Mojave) is (from the ~/fasta36/src directory):

make -f ../make/Makefile.os_x86_64 all

This will make ../bin/glsearch36 and ../bin/ggsearch36 (as well as the other programs).

**Comment by gaboentropy** [comment]
Yes. Sorry. I was using the wrong Makefile and the compilation would fail before producing those programs. Thanks!
