### ISSUE TITLE
use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'

### ISSUE THREAD

**Issue by tseemann** [wrpearson/fasta36#20]
Not critical, but would be good to fix:

```
ld: compacc2_t.o: in function `build_lib_db':
compacc2e.c:(.text+0x3147): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
```

Compiling current `h` version.

**Comment by wrpearson** [comment]
As much as I would like to fix this, mktemp() is the correct function in this case.  The filename created is used as part of a shell script, so it is required as a name, not an open file descriptor (which would cause the script to fail).

**Comment by tseemann** [comment]
I believe those functions modify the `char* template` string to be the generated unique filename, so that could be passed to the shell script.

What's unclear is if the template is not a full path, and it honours `$TMPDIR` for the root, how one would ensure the full pathname was passed to the shell script.

**Comment by wrpearson** [comment]
Yes, mkstemp() could be used (because it provides the filename), but to actually use the file, the file descriptor would have to be closed, and then we would be back to the security issue that generates the warning for mktemp().

Bill Pearson


Begin forwarded message:
