### ISSUE TITLE
Parseable output format (-m 10): wrong scores printed for subsequent hit

### ISSUE THREAD

**Issue by flange-ipb** [wrpearson/fasta36#30]
Hello,

in case a library sequence produces more than one alignment hit, the scoring printed for the subsequent hit (alignment starts with ">--") is the one of the first hit, which is incorrect. I observe this for output format 10, but not for the standard format 0.

Files for reproduction:
[library](https://github.com/wrpearson/fasta36/files/6507580/data.fasta.txt) and [query](https://github.com/wrpearson/fasta36/files/6507589/query.fasta.txt)

Result examples:
[output format 10](https://github.com/wrpearson/fasta36/files/6507595/results_m10.txt): compare lines 116-118 (first hit) with lines 150-152 (second hit, incorrect scores)
[output format 0](https://github.com/wrpearson/fasta36/files/6507617/results_m0.txt): compare line 61 (first hit) with line 77 (second hit, correct scores)

Best regards,
Frank

**Comment by wrpearson** [comment]
Frank --

I have found and fixed the problem, and hopefully will be able to upload the changes to GitHub in the next day or so (unfortunately I will have much less internet connectivity for the next month).

Here is the required change:

diff --git a/src/mshowalign2.c b/src/mshowalign2.c
index 513424f..1e5b20a 100644
--- a/src/mshowalign2.c
+++ b/src/mshowalign2.c
@@ -748,9 +748,9 @@ void showalign (FILE *fp, unsigned char **aa0, unsigned char *aa1save, int maxn,
        if (info_str[0]) fprintf(fp,"; %s_info: %s\n",m_msp->f_id0,info_str);
        if (ppst->zsflag>=0) 
          fprintf (fp,"; %s_z-score: %4.1f\n; %s_bits: %3.1f\n; %s_expect: %6.2g\n",
-                  m_msp->f_id0,bbp->zscore,
-                  m_msp->f_id0,zs_to_bit(bbp->zscore, m_msp->n0, bbp->seq->n1),
-                  m_msp->f_id0,bbp->rst.escore);
+                  m_msp->f_id0,lzscore,
+                  m_msp->f_id0,zs_to_bit(lzscore, m_msp->n0, bbp->seq->n1),
+                  m_msp->f_id0,zs_to_E(lzscore, bbp->seq->n1, ppst->dnaseq, ppst->zdb_size, m_msp->db));
 #else
        if ((m_msp->markx & MX_M11OUT) == 0) {
          fprintf (fp,"; %s_%s: %d\n", m_msp->f_id0, m_msp->alab[0], lsw_score);



Bill Pearson

**Comment by flange-ipb** [comment]
Hello Bill,

excellent! This patch solves the issue.

Thanks for your quick support!
Frank

**Comment by wrpearson** [comment]
Corrected in latest v36.3.8 version
