### ISSUE TITLE
Missing sequence in fasta query file results in infinite loop

### ISSUE THREAD

**Issue by flange-ipb** [wrpearson/fasta36#38]
Hello again,

the following malformed fasta query files lead to infinite loops:
```
>query
SAVQQKLAALEKSSGGRLG
>VALIDTADNTQVLYRGDERFPMCSTSKVMAA
```
or just
```
>query
```
I intentionally added no new line at the end.
As I'm developing a web service that executes fasta programs, this could be input from users and can result in denial of service.

The good news is: Univ. of Virginia's FASTA server filters the malformed entry and EBI's FASTA search drops a validation error.

Best regards,
Frank

**Comment by wrpearson** [comment]
This was fixed in v36.3.8 in 2022
