### ISSUE TITLE
Win Comp Error

### ISSUE THREAD

**Issue by Zombach** [wrpearson/fasta36#47]
![image](https://user-images.githubusercontent.com/52016832/205263518-5c769828-0de1-4b1f-9725-f37b59774fbc.png)
compacc2_s.obj : error LNK2019: unresolved external symbol  _mkstemp in func _build_lib_db.
How to fix?
add include? What, and most importantly where?

**Comment by wrpearson** [comment]
The compacc2e.c/build_lib_db() function should be disabled if you are not in the UNIX environment:


--- a/src/compacc2e.c
+++ b/src/compacc2e.c
@@ -1577,6 +1577,10 @@ build_lib_db(char *script_file) {
   int lib_db_str_len;
   char *bp, *lib_bp;
 
+#ifndef UNIX
+  return 0;
+#else
+
   if ((lib_db_file=(char *)calloc(MAX_STR,sizeof(char)))==NULL) {
     fprintf(stderr,"*** ERROR [%s:%d] - [build_lib_db] Cannot allocate lib_db_file",
            __FILE__, __LINE__);
@@ -1662,6 +1666,7 @@ build_lib_db(char *script_file) {
 
  no_lib:
   return NULL;
+#endif
 }
 
 /* used to temporarily allocate annotation array in next_annot_entry()*/

**Comment by wrpearson** [comment]
The compacc2e.c code has been modified to disable build_lib_db() outside the UNIX environment.
