### ISSUE TITLE
Cannot allocate buffer 3000002

### ISSUE THREAD

**Issue by Zombach** [wrpearson/fasta36#49]
Hi. How to increase the buffer? Base size ~400mb

FASTA searches a protein or DNA sequence data bank
 version 36.3.8i Nov, 2022
Please cite:
 W.R. Pearson & D.J. Lipman PNAS (1988) 85:2444-2448

 (karlin lambda) non-negative expected score: 0.75
*** ERROR [comp_lib9.c:2155]: cannot allocate buffer 3000002

![image](https://user-images.githubusercontent.com/52016832/213156116-be606f1f-737c-49a8-8a27-32cec9e27d09.png)

extended options -XM=MySize ?

**Comment by Zombach** [comment]
> Hi. How to increase the buffer? Base size ~400mb
> 
> FASTA searches a protein or DNA sequence data bank version 36.3.8i Nov, 2022 Please cite: W.R. Pearson & D.J. Lipman PNAS (1988) 85:2444-2448
> 
> (karlin lambda) non-negative expected score: 0.75 *** ERROR [comp_lib9.c:2155]: cannot allocate buffer 3000002
> 
> ![image](https://user-images.githubusercontent.com/52016832/213156116-be606f1f-737c-49a8-8a27-32cec9e27d09.png)

extended options -XM=MySize ?

**Comment by wrpearson** [comment]
The message "cannot allocate buffer ..." is coming from a failed attempt to allocate a buffer of that size. It is a limitation of your computer/operating system.

To avoid this message, you should ask to allocate less memory, not more.  This number can be decreased with the -XM option.

The karlin lambda message indicates a problem with your scoring matrix.  You need to make negative values more negative.

Bill Pearson

Begin forwarded message:


From: ZLoo ***@***.******@***.***>>

Subject: Re: [wrpearson/fasta36] Cannot allocate buffer 3000002 (Issue #49)

Date: January 18, 2023 at 6:15:15 AM EST

To: wrpearson/fasta36 ***@***.******@***.***>>

Cc: Subscribed ***@***.******@***.***>>

Reply-To: wrpearson/fasta36 ***@***.******@***.***>>


Hi. How to increase the buffer? Base size ~400mb

FASTA searches a protein or DNA sequence data bank version 36.3.8i Nov, 2022 Please cite: W.R. Pearson & D.J. Lipman PNAS (1988) 85:2444-2448

(karlin lambda) non-negative expected score: 0.75 *** ERROR [comp_lib9.c:2155]: cannot allocate buffer 3000002

[image]<https://user-images.githubusercontent.com/52016832/213156116-be606f1f-737c-49a8-8a27-32cec9e27d09.png>

extended options -XM=MySize ?
