### ISSUE TITLE
Feature request: add query and subject length to tabular output

### ISSUE THREAD

**Issue by yzhang-github-pub** [wrpearson/fasta36#50]
Dr. Pearson,

Many times I need to know alignment coverage in addition to  sequence similarity. Several of my colleagues also need such a feature. What we do is to generate -m8 output first, then add length information to the output. Could you add query and subject length to -m8 output as a new format, such as -m 8D? Thank you for your consideration.

**Comment by wrpearson** [comment]
The -m8 option can also show query and subject lengths by adding ‘l’ or ‘L’ at the end.  I am away from my computer, but I routinely use -m8CBl to show both the blast alignment encoding and the query and subject lengths.

Bill Pearson

On Feb 9, 2023, at 3:31 AM, yzhang-github-pub ***@***.***> wrote:

﻿

Dr. Pearson,

Many times I need to know alignment coverage in addition to sequence similarity. Several of my colleagues also need such a feature. What we do is to generate -m8 output first, then add length information to the output. Could you add query and subject length to -m8 output as a new format, such as -m 8D? Thank you for your consideration.

**Comment by yzhang-github-pub** [comment]
Thank you for your quick response!
