### ISSUE TITLE
remark about the help message regarding the matrices (option -s)

### ISSUE THREAD

**Issue by peutch** [wrpearson/fasta36#52]
Hi,

The current help message (using fasta36 --help) is:
```
 -s:  Scoring matrix: (protein)
      BL50, BP62 (sets -f -11 -g -1); P250, OPT5, VT200,
      VT160, P120, VT120, BL80, VT80, MD40, VT40, MD20, VT20, MD10, VT10;
      scoring matrix file name; -s ?BL50 adjusts matrix for short queries;
```
Adding BL62 before BP62 could help to remind the first and their relationship, no?

Also,  it is not clear to me if VT160 is data/VTML_160.mat or data/vtml160.mat (OPT5?).

Many thanks!

**Comment by wrpearson** [comment]
VT160 is the same as VTML_160 -- a modern series of PAM matrices optimized for a distance of PAM160.  OPT5 is a matrix produced by  Kann et al. (2000) Proteins 41:498-503.  Checking the code in upam.h, I see that the -s VT160 matrix uses the parameters in data/vtml160.mat, while the other VT matrices use the values in data/VTML_XXX.mat.

I edited the help message on the scoring matrix option to mention BL62 (although, in the process, I noticed that for some time, by mistake, BL62 and BP62 have behaved identically).

**Comment by peutch** [comment]
Hi,
Here is a fix to update data/README.md based on the discussion of this issue.
To be more clear, I replaced some names by uppercase w.r.t. their corresponding filenames (useful for case-sensitive filesystem). I also added the missing VT200 to the same rank as listed in upam.h.
Best regards,
Patrice

[data_README_patch.txt](https://github.com/user-attachments/files/19430171/data_README_patch.txt)
