### ISSUE TITLE
make:  error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by doctorbrassica** [wrpearson/fasta36#58]
I get this error doing make on a Google Cloud instance. All the compiles fail, except for fasta36.

It goes away if I add this to gcc in the Makefile:
-std=c99

Would you be amenable to a PR to fix this?

**Comment by wrpearson** [comment]
-std=c99 has been added to Makefile.linux64_sse2 and other Makefile.linux make files.
