### ISSUE TITLE
lalign36 segmentation fault

### ISSUE THREAD

**Issue by ehgunther** [wrpearson/fasta36#61]
I tried running the lalign program on two protein sequence fasta files and it gave a segmentation fault error. 

`>  /home/user/v36.3.8/bin/lalign36 -s BP62 -T 1 -b 1 -f 0 -g 0 -z -1 -m 9c /filepath/to/fasta1 /filepath/to/fasta2`
and the output was:

```
# /home/user/v36.3.8/bin/lalign36 -s BP62 -T 1 -b 1 -f 0 -g 0 -z -1 -m 9c /filepath/to/fasta1 /filepath/to/fasta2
LALIGN finds non-overlapping local alignments
 version 36.3.8i May, 2023
Please cite:
 X. Huang and W. Miller (1991) Adv. Appl. Math. 12:373-381

Segmentation fault
```

I tried running the same inputs with ssearch36 in place of lalign36 and everything worked fine. 
This was on Ubuntu 22.04.3 LTS running in a Docker container.

**Comment by wrpearson** [comment]
I am traveling and will not be able to look into this for a few weeks.

That said, I can imagine that the lalign algorithm is not robust to alignments with 0 gap open and gap extend penalties.

Bill Pearson

On Mar 13, 2024, at 7:05 AM, Elijah Gunther ***@***.***> wrote:

﻿

I tried running the lalign program on two protein sequence fasta files and it gave a segmentation fault error.

> /home/user/v36.3.8/bin/lalign36 -s BP62 -T 1 -b 1 -f 0 -g 0 -z -1 -m 9c /filepath/to/fasta1 /filepath/to/fasta2
and the output was:

# /home/user/v36.3.8/bin/lalign36 -s BP62 -T 1 -b 1 -f 0 -g 0 -z -1 -m 9c /filepath/to/fasta1 /filepath/to/fasta2
LALIGN finds non-overlapping local alignments
 version 36.3.8i May, 2023
Please cite:
 X. Huang and W. Miller (1991) Adv. Appl. Math. 12:373-381

Segmentation fault


I tried running the same inputs with ssearch36 in place of lalign36 and everything worked fine.
This was on Ubuntu 22.04.3 LTS running in a Docker container.
