### ISSUE TITLE
How I can intall fast36?

### ISSUE THREAD

**Issue by Shyer-coma** [wrpearson/fasta36#65]

**Comment by wrpearson** [comment]
Without knowing what system you want to run the fasta package on, it is difficult to answer your question.  Compiled binaries are available for MacOS, and Linux64, with an older version for Windows.  The FASTA programs must be run from a command line.  To recompile the MacOS and Linux versions, you would un-tar the source distribution (fasta.tar.gz) into an empty directory,
```
cd src
make ../make/Makefile.os_x??? all
```
and the programs are compiled into the ```../bin``` directory.
