### ISSUE TITLE
alignment score and Evalue calculation?

### ISSUE THREAD

**Issue by biocyberman** [wrpearson/fasta36#8]
I am skimming through the source code because the documentation (`fasta_guide.pdf`) does not give good explanations. However, it will be much more helpful if you @wrpearson could provide relevant code segments and formulae for the following: 
Alignment score and Evalue calcuation for:
 1. global-global alignment (GGSEARCH) Needleman-Wunsch algorithm
2. local alignment (SSEARCH) Smith-Waterman algorithm

Thanks

**Comment by wrpearson** [comment]
I am afraid that I do not understand what you would like to have.

The alignment score and E()-values are shown in the output.  For ggsearch36, the alignment score is calculated by the do_work() function in the dropnnw2.c file, for ssearch36, the score is calculated by do_work() in the dropgsw2.c file.

The E()-value calculation for local scores is done by functions in scaleswn.c.  ssearch and other local comparison methods use the extreme value distribution.  ggsearch uses a normal distribution to calculate the significance of global alignment scores.

Bill Pearson

Begin forwarded message:

**Comment by biocyberman** [comment]
Thanks for the pointers, Bill. The filenames you gave are very helpful. In addition to that, what are recommended readings to understand about algorithms used in FASTA36 ?
