### ISSUE TITLE
incomplete results with glsearch36

### ISSUE THREAD

**Issue by misik** [wrpearson/fasta36#9]
Hi,

I have two datasets (reference genome and SNP/INDEL dataset) where I am searching for a single pattern and comparing the found patterns to see how the SNP has effected the found pattern. I found out that some of the found patterns in SNP dataset cannot be found in reference genome, even if it is a single SNP. Interestingly, when I run the glsearch only with that 90bp sequence from reference genome, the pattern can be found. So I am guessing it is related to the database size. I tried to change database size to 1, 550, 100 million (by using -Z parameter), but it did not have much effect of the found results. The -E parameter is set to 10e+100. 
I set the -z 0, to avoid normalization to sequence length but I also tried -z 1, -z 2, -z 6 and some others. None of them worked. 

I concatenated the two databases (hg38 and variation) to avoid the difference in database size, but the problem remained. 

The reference genome sequences are 90bp long fasta sequences. (~60 million sequences in total)
The SNP/INDEL dataset has variable length sequences (60bp minimum (most common size), several hundreds) (~90 million sequences in total).

version: fasta-36.3.8g

The command is:

$FASTA36_HOME/glsearch36 -L -E 10e+100 -b 10000000000000000000 -f 5 -g 5 -T 18  -s dna_adj5.mat -z 0 -Z 100000000000 -m BB -ktup=1 -q pattern.fa ../merged_hg38_variation.fa

The dna.mat is adjusted because I would like to find patterns that match the 5'end of the pattern strongly. So I changed the letters at 5' end of pattern to K,R and adjusted M,K,R,Y letters to have higher scores if they match C,G, (G,A) and (C,T), respectively. 

However, this should not be a problem because, as mentioned above, I can find the pattern when I use the fasta file with one sequence only and same matrix. 

So I'd like to know:
1. What can be the reason why the pattern cannot be found in one of the datasets when the whole database is searched?

2. Can I use a PSSM matrix and dna.mat together instead of modifying the dna.mat to make the search more sensitive for 5' end?

3. Is it possible to add new letters to the matrix instead of changing M,K,R,Y? I tried this but it seemed not to work? I'd like to change the 5'end of the matrix with letters that are not present in the dna.mat and add those letters to dna.mat manually to make the 5' end to be searched independently.   

4. Is setting -z to 0 enough to find patterns without normalization to sequence length?

Thank you,
Meltem

**Comment by wrpearson** [comment]
FASTA only saves 60,000 high scores, regardless of the size of the database.  You can see ALL of the result scores (but not alignments) using the "-R results.file" option.
